### ISSUE TITLE
add a key based access

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/marteau#13]
We want scripts to be able to work with a marteau server without interacting with browser-id

We should generate a secret key per user that can be used by the command line calls

I guess oauth

**Comment by almet** [comment]
I don't get how this is related to marteau? do you have a workflow in mind ?

**Comment by tarekziade** [comment]
This adds a job in a Marteau serevr

``` bash
$ marteau https://github.com/mozilla-services/tokenserver --server http://marteau.example.com
```

It's broken because the API requires an authentication header -- currently Browser ID

If we add a key-based auth we will be able to do this:
1. log in to the marteau server
2. generate an API key associated to your user
3. use the key to auth.

``` bash
$ export MARTEAU_API_KEY = dwqkjdbwqkjdbwqkjhdbwqqwhvdwqkjbdwq
$ marteau https://github.com/mozilla-services/tokenserver --server http://marteau.example.com
```

**Comment by tarekziade** [comment]
Done

**Comment by anentropic** [comment]
How is this supposed to work?

I have signed up for a Browser ID and signed in at persona.org

Going to the `/profile` of my marteau server there is a link to "sign in with Browser ID"

this goes through to `/sign` page on my server... which returns 403 forbidden

I'm not familiar with Pyramid... am I missing doing something like Django's create_superuser step or is it a Browser ID problem?

**Comment by tarekziade** [comment]
> this goes through to /sign page on my server... which returns 403 forbidden

this is weird - did you end up in the persona popup, then back to the website ? what is the exact error you are getting ?

**Comment by anentropic** [comment]
no popup, no other error, just straight to the bare 403 returned from my server

**Comment by tarekziade** [comment]
I am installing a new marteau server from scratch - will let you know if I can reproduce. If not we'll dig

**Comment by anentropic** [comment]
maybe document the correct way to start up the marteau server if there's any tricky parts to note

I was running under supervisord like this:

```
{virtualenv_path}/bin/marteau-serve --host {node['marteau-server']['host']} --port {node['marteau-server']['port']}
```

**Comment by tarekziade** [comment]
yeah I am writing a step-by-step install guide. 

in your line you miss:

```
--config marteau/marteau.ini
```

**Comment by anentropic** [comment]
ah, my bad, the `marteau.ini` in the repo had a bunch of stuff that looked very specific to your own use, like maybe it was a file that got committed by accident, so I ignored it  :)

(I was mostly in a hurry this week just to get some load tests running at work, didn't look too deeply)
