### ISSUE TITLE
support for mercurial repositories

### ISSUE THREAD

**Issue by rfk** [mozilla-services/marteau#14]
So I can point marteau at https://hg.mozilla.com/services/server-storage and have it all just work :-)

**Comment by tarekziade** [comment]
Good idea. btw - can't we use https://github.com/mozilla-services/server-syncstorage ?

**Comment by cloudmatrix** [comment]
That's the sync2.0 repository, the sync1.1 codebase is still in mercurial.

**Comment by rfk** [comment]
oops, was logged into github on a different account...
