### ISSUE TITLE
fixtures required

### ISSUE THREAD

**Issue by redsnapper8t8** [mozilla-services/marteau#17]
Marteau is bombing out in job.py on line 133 due to a lack of fixtures. 
These are not documented anywhere.

**Comment by redsnapper8t8** [comment]
(marteau2env)root@E6320:~/marteau2env# bin/marteau loadtests/
2013-01-03 11:44:14 [7179] [INFO] Hammer ready. Where are the nails ?
2013-01-03 11:44:14 [7179] [INFO] Bye!
Traceback (most recent call last):
  File "bin/marteau", line 8, in <module>
    load_entry_point('marteau==0.1', 'console_scripts', 'marteau')()
  File "/root/marteau2env/local/lib/python2.7/site-packages/marteau/job.py", line 371, in main
    fixture_options=args.fixture_options)
  File "/root/marteau2env/local/lib/python2.7/site-packages/marteau/job.py", line 106, in _std
    return func(_args, *_kwargs)
  File "/root/marteau2env/local/lib/python2.7/site-packages/marteau/job.py", line 118, in _cleanup
    return func(_args, *_kwargs)
  File "/root/marteau2env/local/lib/python2.7/site-packages/marteau/job.py", line 135, in run_loadtest
    for fixture in options.get('fixtures', []):
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by redsnapper8t8** [comment]
adding a try accept gets me as far as 
"Running the fixture tear_down method"

**Comment by tarekziade** [comment]
this is probably a regression of the CLI script, since we're mostly using the web app these days.

I'll have a look right now, thx for the feedback

**Comment by tarekziade** [comment]
I can reproduce, I'll fix it now

**Comment by tarekziade** [comment]
@redsnapper8t8  let me know how it goes

**Comment by redsnapper8t8** [comment]
@tarekziade  Sorry, I ca't get it to work at all
Running the Stupidtest from https://github.com/mozilla-services/marteau/blob/master/marteau/tests/StupidTest.conf

The test works when run through funkload but not through marteau

(marteau2env)root@E6320:~/marteau2env# bin/marteau `pwd`/loadtests/
2013-01-03 14:08:46 [9845] [INFO] Hammer ready. Where are the nails ?
Moved to '/root/marteau2env/loadtests/'
virtualenv --no-site-packages .
Using real prefix '/usr'
New python executable in ./bin/python
Installing setuptools.............done.
Installing pip...............done.
/root/marteau2env/bin/python -c 'from pip import runner; runner.run()' install funkload
Requirement already satisfied (use --upgrade to upgrade): funkload in /root/marteau2env/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): webunit>=1.3.8 in /root/marteau2env/lib/python2.7/site-packages (from funkload)
Requirement already satisfied (use --upgrade to upgrade): docutils>=0.3.7 in /root/marteau2env/lib/python2.7/site-packages (from funkload)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /root/marteau2env/lib/python2.7/site-packages (from funkload)
Cleaning up...
Running the loadtest
/root/marteau2env/bin/python -c 'from funkload.BenchRunner import main; main()' loadtest.py StupidTest.test_simple
test_simple:0:0:0: [main] title not found
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/marteau2env/local/lib/python2.7/site-packages/funkload/BenchRunner.py", line 716, in main
    bench = BenchRunner(args[0], klass, method, options)
  File "/root/marteau2env/local/lib/python2.7/site-packages/funkload/BenchRunner.py", line 225, in **init**
    self.class_title = test.conf_get('main', 'title')
  File "/root/marteau2env/local/lib/python2.7/site-packages/funkload/FunkLoadTestCase.py", line 667, in conf_get
    val = self._config.get(section, key)
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
===loadtest===
test_simple:0:0:0: [bench] sleep_time_min not found
test_simple:0:0:0: [bench] sleep_time_max not found
test_simple:0:0:0: [bench] log_to not found
test_simple:0:0:0: [bench] log_path not found
test_simple:0:0:0: [bench] result_path not found
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'main'
"/root/marteau2env/bin/python -c 'from funkload.BenchRunner import main; main()' loadtest.py StupidTest.test_simple" failed
Running the fixture tear_down method
2013-01-03 14:08:47 [9845] [INFO] Bye!
Traceback (most recent call last):
  File "bin/marteau", line 8, in <module>
    load_entry_point('marteau==0.1', 'console_scripts', 'marteau')()
  File "/root/marteau2env/local/lib/python2.7/site-packages/marteau/job.py", line 372, in main
    fixture_options=args.fixture_options)
  File "/root/marteau2env/local/lib/python2.7/site-packages/marteau/job.py", line 104, in _std
    return func(_args, *_kwargs)
  File "/root/marteau2env/local/lib/python2.7/site-packages/marteau/job.py", line 116, in _cleanup
    return func(_args, *_kwargs)
  File "/root/marteau2env/local/lib/python2.7/site-packages/marteau/job.py", line 260, in run_loadtest
    run_func(queue, job_id, '%s %s %s' % (cmd, script, test))
  File "/root/marteau2env/local/lib/python2.7/site-packages/marteau/job.py", line 82, in run_func
    raise Exception("%r failed" % cmd)
Exception: "/root/marteau2env/bin/python -c 'from funkload.BenchRunner import main; main()' loadtest.py StupidTest.test_simple" failed

*
*
*
*

(marteau2env)root@E6320:~/marteau2env# /root/marteau2env/bin/python -c 'from funkload.BenchRunner import main; main()' loadtest.py StupidTest.test_simple

# ===loadtest===

# Benching StupidTest.test_simple

## Access 9 times the main url

# Configuration
- Current time: 2013-01-03T14:11:49.623269
- Configuration file: /root/marteau2env/StupidTest.conf
- Log xml: /root/marteau2env/simple-bench.xml
- Server: http://google.com
- Cycles: [1, 2, 3]
- Cycle duration: 5s
- Sleeptime between request: from 0.0s to 0.5s
- Sleeptime between test case: 0.0s
- Startup delay between thread: 0.0s

# Benching
- setUpBench hook: ... done.

## Cycle #0 with 1 virtual users
- setUpCycle hook: ... done.
- Current time: 2013-01-03T14:11:49.629012
- Starting threads: ===loadtest===
  . done.
- Logging for 5s (until 2013-01-03T14:11:54.632789): ............... done.
- Waiting end of threads: . done.
- Waiting cycle sleeptime 0s: ... done.
- tearDownCycle hook: ... done.
- End of cycle, 5.11s elapsed.
- Cycle result: **SUCCESSFUL**, 15 success, 0 failure, 0 errors.

## Cycle #1 with 2 virtual users
- setUpCycle hook: ... done.
- Current time: 2013-01-03T14:11:54.737671
- Starting threads: ===loadtest===
  .===loadtest===
  . done.
- Logging for 5s (until 2013-01-03T14:11:59.745342): ............................. done.
- Waiting end of threads: .. done.
- Waiting cycle sleeptime 0s: ... done.
- tearDownCycle hook: ... done.
- End of cycle, 5.15s elapsed.
- Cycle result: **SUCCESSFUL**, 29 success, 0 failure, 0 errors.

## Cycle #2 with 3 virtual users
- setUpCycle hook: ... done.
- Current time: 2013-01-03T14:11:59.885621
- Starting threads: ===loadtest===
  .===loadtest===
  .===loadtest===
  . done.
- Logging for 5s (until 2013-01-03T14:12:04.896926): ......................................... done.
- Waiting end of threads: ... done.
- Waiting cycle sleeptime 0s: ... done.
- tearDownCycle hook: ... done.
- End of cycle, 5.30s elapsed.
- Cycle result: **SUCCESSFUL**, 41 success, 0 failure, 0 errors.
- tearDownBench hook: ... done.

# Result
- Success: 85
- Failures: 0
- Errors: 0

Bench status: **SUCCESSFUL**

**Comment by tarekziade** [comment]
@redsnapper8t8 that did work in fact. You've successfully ran a load test from the CLI.

Now if you want to run a marteau server you need to run:

``` bash
$ marteau-serve --config marteau/marteau.ini
```

**Comment by tarekziade** [comment]
Oh I did not see the TB. Keep in mind that you need to provide a github  repo or a local directory, than contains the yml file. like:

``` bash
$ bin/marteau https://github.com/mozilla-services/marteau
```

**Comment by tarekziade** [comment]
@redsnapper8t8  still having trouble ? let me know if you need help
