### ISSUE TITLE
Marteau doesn't seem to properly teardown old testsuites

### ISSUE THREAD

**Issue by crankycoder** [mozilla-services/marteau#23]
When testing the heka server with the marketplace, I re-used the old marketplace-loadtest project at:

https://github.com/mozilla/marketplace-loadtest

When I forked the project and made minor modifications and reran the tests in the marteau web interface, the old test code continued to execute.

Once I renamed my project and config files, I got the right code to execute.

New project (for reference) is at:

https://github.com/crankycoder/heka-marketplace-loadtest

**Comment by tarekziade** [comment]
yeah we're keeping a single version on the server for a given project, and just update it with a dumb 'git pull' on master. It's not dealing with branches.

I could add a branch option.
