### ISSUE TITLE
Report fails to build, can't copy "marteau.css"

### ISSUE THREAD

**Issue by rfk** [mozilla-services/marteau#27]
I tried to run picl-server loadtest via the AWS hosted marteau, and the building of the report failed with "IOError: [Errno 2] No such file or directory: '/home/marteau/marteau/marteau/media/marteau.css'".

Is this a problem inside marteau, or something I've mis-configured in my funkload setup?  Full output log here:

  http://marteau.services.mozilla.com/test/c04b90629bd74501ab142f1ffd15fe52

**Comment by tarekziade** [comment]
Sorry I am currently refactoring things and this file should have been moved after. It should work now

I have tried a small run here and it was successful: http://marteau.services.mozilla.com/report/ae086b121bc940bfa79ee7527dfd7891/index.html#request-stats
