### ISSUE TITLE
Error "bash: bin/fl-run-bench: No such file or directory"

### ISSUE THREAD

**Issue by rfk** [mozilla-services/marteau#29]
I had marteau working against AWS picl deployment for about a day, but it's started giving me errors again.  Looks like maybe a problem with installing funkload on the worker nodes?  Full console output:

  http://marteau.services.mozilla.com/test/b1ba431254c943f19690d8b0ed8542f2

**Comment by tarekziade** [comment]
I tweaked your conf so it uses my up-to-date fork of funkload. 

did a successful run at http://marteau.services.mozilla.com/test/254c763f84184ea58d9b57fee877552d
btw the console is now updated in realtime using web sockets

**Comment by rfk** [comment]
Sweet, thanks @tarekziade!

**Comment by rfk** [comment]
For posterity (and for jbonacci) the picl-server commit fixing this issue is here:

  https://github.com/mozilla/picl-server/commit/796edc86030e5182650f0de26e840f583b218440
