### ISSUE TITLE
"OSError: [Errno 12] Cannot allocate memory" while running gnuplot

### ISSUE THREAD

**Issue by rfk** [mozilla-services/marteau#31]
Report building failed at attempt to run gnuplot, saying that it could not allocated enough memory:

```
http://marteau.services.mozilla.com/test/b4df6a5d56b24524b4be4339a792f6b3
```

Will try again and see if it's just a transient thing...

**Comment by rfk** [comment]
Tried running a new job but it just hangs as "waiting for data..."

**Comment by tarekziade** [comment]
mmm I am not sure yet what happened. this looks like the process ran out of fds for some reason but I have no idea why

I wiped the jobs and run again: http://marteau.services.mozilla.com/report/74ba2513915e4017972185be83a6f75e/index.html#request-stats

let me know if you get the issue again!
