### ISSUE TITLE
Troubles installing the gevent dependency

### ISSUE THREAD

**Issue by almet** [mozilla-services/marteau#5]
While installing marteau on my own server, I had some troubles regarding the gevent dependency. This is mainly due to the fact that gevent1.0 is not released yet.

Here is what I done regarding this. I'm opening this ticket more as a note for potential future interested people than a request to fix something in marteau, though.

A quick fix is to get the gevent dependency from the sources, here: https://github.com/schmir/gevent install it in the same environment and then update the version in the setup.py.

What's the reason we are having a dep on non-released gevent? Is there any particular feature that's not in the previous version?

**Comment by anentropic** [comment]
I guess this is the import error on `gevent.subprocess` ...

for anyone else:

```
pip install cython
pip install -I -e git+git://github.com/schmir/gevent.git#egg=gevent
```

**Comment by anentropic** [comment]
Is there also a dependency on HEAD version of `docutils` ?

I am getting this error: http://sourceforge.net/p/docutils/bugs/215/  with the docutils 0.10 which gets installed as a dep

fixed by
`pip install -I -e svn+svn://svn.code.sf.net/p/docutils/code/trunk/docutils#egg=docutils`
