### ISSUE TITLE
Remove the dependency to circus

### ISSUE THREAD

**Issue by almet** [mozilla-services/marteau#6]
I'm not sure why we need to tie directly marteau with circus. While it's a welcome addition in case one would like to have e everything working without too much hassle, I'm not sure we should list circus as a dependency of marteau.

Is there something I'm missing here?

**Comment by tarekziade** [comment]
because I want to offer a single command line to run marteau:

``` bash
$ bin/circusd marteau/marteau.ini
```

I was thinking about adding a marteau-specific command line that does this specifically, using circus APIs

**Comment by almet** [comment]
Yet, I'm not sure that we should _depend_ on circus to do that. It should come as an additional dependency, so that if people want to use it with circus they just have to install circus and "hop", they're all set, but if they want to control their processes in a different way, they don't have un-needed dependencies, since circus doesn't bring any real value tied to the nature of marteau itself, unless I'm wrong :)

**Comment by tarekziade** [comment]
If I add a console script that gets installed with the other scripts we do need it. 

I am not sure why this dependency is an issue btw. ?

**Comment by almet** [comment]
Let's take an example. On my machine, I'm already using another process manager for all the other projects, so I don't want to use circus in place of it, as I'm used to another tool. Marteau doesn't per-se needs circus, so that would be sad to depend on it if it doesn't bring any value in term of features.

Also, circus comes with its set of dependencies and thus add them to the deps of marteau itself. I'm thinking about some low level deps like zmq, which could be a problem.
